# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_CustomWidget(object):
    def setupUi(self, CustomWidget):
        CustomWidget.setObjectName("CustomWidget")
        CustomWidget.resize(1024, 1180)
        self.gridLayout = QtWidgets.QGridLayout(CustomWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plotWidget = PlotWidget(CustomWidget)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(CustomWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)
        self.imageWidget = ImageView(CustomWidget, view=pg.PlotItem())
        self.imageWidget.setObjectName("imageWidget")
        self.gridLayout.addWidget(self.imageWidget, 1, 0, 1, 1)

        self.retranslateUi(CustomWidget)
        QtCore.QMetaObject.connectSlotsByName(CustomWidget)

    def retranslateUi(self, CustomWidget):
        _translate = QtCore.QCoreApplication.translate
        CustomWidget.setWindowTitle(_translate("CustomWidget", "Form"))
        self.checkBox.setText(_translate("CustomWidget", "Mouse Enabled"))
from pyqtgraph import ImageView, PlotWidget
